In [1]:
import numpy as np
import pandas as pd
from textblob import TextBlob

In [2]:
training_data_filename = "../raw_data/fulltrain.csv"
df_train = pd.read_csv(training_data_filename, names=["label", "document"])

In [3]:
# certain models cannot take negative values, so polarity [-1, 1] is padded to [0, 2]
df_train['polarity'] = df_train.document.apply(lambda x: TextBlob(x).sentiment.polarity + 1)
df_train['subjectivity'] = df_train.document.apply(lambda x: TextBlob(x).sentiment.subjectivity)
df_train

,label,document,polarity,subjectivity
0,1,"A little less than a decade ago, hockey fans w...",1.193722,0.487111
1,1,The writers of the HBO series The Sopranos too...,1.087879,0.327652
2,1,Despite claims from the TV news outlet to offe...,1.075720,0.432300
3,1,After receiving 'subpar' service and experienc...,1.121929,0.433119
4,1,After watching his beloved Seattle Mariners pr...,1.157817,0.585132
...,...,...,...,...
48849,4,The ruling Kuomintang (KMT) has claimed owners...,0.962000,0.379000
48850,4,The Taipei city government has encouraged the ...,1.077396,0.480677
48851,4,President Ma Ying-jeou said Friday that a park...,1.074430,0.181448
48852,4,The families of the four people who were kille...,0.926543,0.348457
48853,4,The Ministry of Finance will make public on Sa...,1.050000,0.327083

In [4]:
X_train = pd.DataFrame(df_train, columns=['polarity', 'subjectivity'])
y_train = df_train["label"]